services:
  frontend:
    build: .
    ports:
      - "3000:80"  
    environment:
      - REACT_APP_API_URL=http://backend:8080/api  
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ../backend/nereye
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/rent
      - SPRING_DATASOURCE_USERNAME=springstudent
      - SPRING_DATASOURCE_PASSWORD=springstudent
    #depends_on:
      #- db
    networks:
      - app-network

  #db:
   # image: mysql:8.0
   # environment:
    #  - MYSQL_DATABASE=rent
    #  - MYSQL_USER=springstudent
    #  - MYSQL_PASSWORD=springstudent
    #  - MYSQL_ROOT_PASSWORD=root
    #ports:
    #  - "3306:3306"
    
    #networks:
      #- app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 