version: '3.8'

services:
  backend:
    build: ./backend/nereye
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/rent?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_SECURITY_USER_NAME: demo
      SPRING_SECURITY_USER_PASSWORD: demo
      SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

#  rentdb:
#    image: mysql:8.0
#    restart: always
#    environment:
#      MYSQL_DATABASE: rent
#      MYSQL_USER: springstudent
#      MYSQL_PASSWORD: springstudent
#      MYSQL_ROOT_PASSWORD: springstudent
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "springstudent", "-pspringstudent"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
