version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
