version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Nginx React'ı 80 portunda sunar
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
